### ISSUE TITLE
Issue with build in Microsoft Visual Studio

### ISSUE THREAD

**Issue by msschwei** [inr-kit/McCAD-Library#11]
I am unable to perform the build -> build all step as governed by the McCAD v1.1 installation manual.  I have placed cmake, boost, and the McCAD library in the D: drive and verified that the paths are correct in the command arguments from CMakeSettings.json.  The only thing that shows up under the build option in the Menu is "Run Code Analysis on Solution."  I am unsure if I need a specific file open in Microsoft Visual Studio (I have never used this program before).  Please help if you can.

**Comment by moatazharb** [comment]
Hello. Using Microsoft Visual studio (MSVS) for the first time is indeed frustrating, I have personally been through that confusion stage. There is indeed a "settings" file that MSVS uses and it should be in the source code. It is called "CMakeSettings.json". When opening the folder that contains McCAD source code in MSVS, locate the "CMakeSettings.json" in the "Solution Explorer", open the file and edit the entries there to match your build settings. 
If you have done that already, then you need to "Configure" the project in case it is not configured by default. Navigate to the top menu > Project > Configure Cache. You should get some output and a message saying that configuration succeeded. You can then check that it successfully located the Boost and Open CASCADE libraries. After that, the "Build All" option under "Build" in the top menu should be activated to be used. 

Please, let me know how it goes with the installation.
