### ISSUE TITLE
Unable to run example

### ISSUE THREAD

**Issue by msschwei** [inr-kit/McCAD-Library#12]
I am attempting to run the example SS_-793e-2 from the Command prompt.  After following directions from the manual and editing McCADInputConfig.i I type McCAD run in command prompt and it attempts to load the stp file but nothing happens.  I have tried placing the stp file in various locations (the c drive, within the bin folder) but no luck.  Anyone know where I should place the stp file so it can read it?

**Comment by moatazharb** [comment]
Hello. The input stp file is loaded from where the McCADInputConfig.i file is. Best practice is to place the input stp file in a new folder, generate the config file there, edit the file name in the config file to match your input stp file, then run McCAD.
